[workspace]
resolver = "2"
members = [
    "crates/ttrpg_ast",
    "crates/ttrpg_lexer",
    "crates/ttrpg_parser",
    "crates/ttrpg_checker",
    "crates/ttrpg_interp",
    "crates/ttrpg_cli",
    "crates/ttrpg_ose_data",
]
