[package]
name = "ttrpg_interp"
version = "0.1.0"
edition = "2021"

[dependencies]
ttrpg_ast = { path = "../ttrpg_ast" }
ttrpg_checker = { path = "../ttrpg_checker" }

[dev-dependencies]
ttrpg_parser = { path = "../ttrpg_parser" }
